# Generated by Django 4.0.6 on 2022-09-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usertheme_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
